hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 6000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: rating-service
        uri: lb://rating-service
        predicates:
        - Path=/api/ratings/**
        filters:
        - StripPrefix=1
        - RewritePath=/api/(?<ratings>.*), /$\{ratings}
        - AddRequestHeader=X-first-Header, first-service-header
        - name: Hystrix
          args:
            name: ratingsFallbackCommand
            fallbackUri: forward:/fallback/ratings
                   
           

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true
    
    
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
    



#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

